"""empty message

Revision ID: 895fbf9fbfdd
Revises: 
Create Date: 2021-03-31 15:10:12.903197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895fbf9fbfdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Resource',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('max', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('Task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('finish', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tasks_Resources',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('resource_name', sa.String(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['resource_name'], ['Resource.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['Task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'resource_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tasks_Resources')
    op.drop_table('Task')
    op.drop_table('Resource')
    # ### end Alembic commands ###
